set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @theme_transparent_status_bar 'true'
set-option -g status-position bottom

unbind C-b
set -g prefix C-space
bind C-space send-prefix
set -g history-limit 9999999
set -g mode-keys vi
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

unbind c
bind c new-window -c "#{pane_current_path}"

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n S-Left  previous-window
bind -n S-Right next-window

bind-key -T copy-mode-vi Home send-keys -X page-up
bind-key -T copy-mode-vi End send-keys -X page-down

unbind-key -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel


# Style
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold]#S #[fg=${gray_light},nobold] | "
set -g status-right "#(~/.config/tmux/scripts/sysstats.sh)  #[fg=${gray_medium}]#(date +'%a %b %d %H:%M')"
set -g window-status-current-format "#[fg=${cyan_soft},bold]  #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag, 󰍋 ,}"
set -g window-status-format " #I:#W"
set -g message-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${green_soft}"

run '~/.tmux/plugins/tpm/tpm'
